[project]
name = "mcp-terminal"
version = "1.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.2",
    "pydantic>=2.11.7",
]
[project.scripts]
mcp-terminal = "terminal.main:main"